#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
    
runcmd:
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /home/azureuser/key.txt
  - apt-key add /home/azureuser/key.txt
  - rm /home/azureuser/key.txt
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - mkdir /home/azureuser/uccData
  - curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker-compose --file /home/azureuser/docker-compose.yml up &


final_message: "The system is finally up, after $UPTIME seconds"
