#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

write_files:
  - content: |
      ---
      version: "2.1"
      services:
        unifi-controller:
          image: ghcr.io/linuxserver/unifi-controller
          container_name: unifi-controller
          environment:
            - PUID=1000
            - PGID=1000
            - MEM_LIMIT=1024M #optional
          volumes:
            - /home/azureuser/uccData:/config
          ports:
            - 3478:3478/udp
            - 10001:10001/udp
            - 8080:8080
            - 8443:8443
            - 1900:1900/udp #optional
            - 8843:8843 #optional
            - 8880:8880 #optional
            - 6789:6789 #optional
            - 5514:5514/udp #optional
          restart: unless-stopped
    path: /home/azureuser/docker-compose.yml

    
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /home/azureuser/key.txt
  - apt-key add /home/azureuser/key.txt
  - rm /home/azureuser/key.txt
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - mkdir /home/azureuser/uccData
  - curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker-compose --file /home/azureuser/docker-compose.yml up &


final_message: "The system is finally up, after $UPTIME seconds"
