#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - npm

#Public key for github.com 
#Generate with ssh-keyscan github.com >> github.com.pub
#Check fingerprint with ssh-keygen -lf github.com.pub
#Compare fingerprint against the fingerprint posted on github.com
write_files:
  - content: |
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    path: /etc/ssh/ssh_known_hosts
    
#Git repo deployment key and public key 
ssh_keys:
  rsa_private: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIG5QIBAAKCAYEA0ASC5GeVxB3anVWGqpc9GqxcMDljlOV/6NXHrapx4+sN3u/d
    D5Qz6LssRb5fJoR193XRFFJKuFpLAI3efYIkuE69xCoF09JCyC7aaQpCXw4R6Qyy
    GG+8h86xAB/By/O45QIQsLVyG9v/U/0A6rplExIdcFdIhjANt/HGiHp21jYx0w7s
    FVD7+7VDXHUxcLHl7tKW5VPRjcG9kDt88iweqDIlx4772dBK7R82/VZIxJyOkEaB
    Lg7giSSBqzy6hkA7ltkRyBxZ5XHC9F9zkGP1Hfz8sv8Ldil/nXEMSiOt0uJ/QlyS
    9teJq5clE8/mmCX9Ve24y7fTHg8A2jJXyj745Uou0vyAnOCr4Gxs/K7RORq5jAEJ
    HEBIgMzxu+jIY9tUfxHx2yEjRvmpiWJKtS1mi5XJW6Ps6cEjVCkRP1hGXMIgj9nY
    JvbZ/7XSsA+ExtvTtFUExO+EsruILt5Ug00Seo5YPP3g5FtPwHGGJ9TnuRiyW1ZT
    8/qCIoKze11o0cvvAgMBAAECggGBAMsNrEuSxcHztmPgiZzaFt6Do1W7n3ZH9Gzu
    yYS/nX7zAs487Ff5vhYPJ29JHo51vMV7L0Wb8q40DYST97wiHv/+dQUYVCnp1CCe
    g7sHNbSeAmOwbeSmpa0X2PWbCkyxMynwsyQbajDBtmJg1NVMb7+G7k+sE/JQ1ANb
    sgWlLX1613YD2fYQ4Hha/08wYrt0HFPdI0jmYebzWLyDJTssUBy1HuXGsBd1WL5Q
    uxfecxfhDtTMzeqMwSd+CEmD9Tt5VC0WDfhEnjIUMn+wAaaohYAoDrty8aeGL1Ax
    2aFAQ5N0lBjOWrandZfOgzwVsAcj4isljmBy/APzPSzBiqIDFoAg03lB5ThY47sq
    NmSyHaCFScvNnhDdAuuKs2JItVNQL/4LxszaAYsTv+V4ujTacOvvpgaIqz4oTYet
    I9Gbzo8tsS6OZZuNMn9cggpHmHEJN8KPv3X1tk8VP18VEUptfgth23pJLUy7qFct
    D3FmLJr1/DuMOXUuyXuXCSVeMfh8wQKBwQD+FpM07FymYulX5EbJs6e0nk0l3/HC
    NIIwXO1JlEO4glrV/vCi5uv7M9kowAYuAeUV7tWEpRFtnw0Vq2gjoc3eipnKJD0/
    klMPsJdp6sK0F442X9doYfGuUM4koU9x5wCWs7O2kanskJlRsKibUoxqgrRT/Eno
    69qAVJMEPuVXyMkezx1PeIPPVMZiBFVnMnePnpb+Y5T+FZ7zV+eVF+bPjwRwfTiT
    1nTrajGxVV9/OyCdFZ9g5rRq80K3oYdk8iECgcEA0ZUx8gFOxRnaNT1U2rhu5R+0
    II2QBeNhEQ0WOua4UTCn8fv8oD5Pz6QA8baP/1QKrh1+n4Zvf7EVTD/eXH/yGPRp
    /v27qINpuvPoXp4o0O3CTD1z3VZzYEQo4p5c11haTSvtFxFJh1YQPZ0nYwwT5mpf
    AiVOgBOeulAG+DRUZe4NJjQ7D2C7Y7JcWwCrc5VVEb4ZlteAzsTVlDNkmuGkNhiw
    yyKnzXvd4dEBKXJ7jFNwMeRHQj8MEuaZKwMZ7BwPAoHBANByqr+fLP8fZDlDwEMX
    DP1jZP0udIKTWz7b7ZsQdGI5JtYqeTXbZjtGNOB2cFtsGIlez3IrjVm2QyDE5wFc
    a60nXbV0935gx522jPFKtALU1EmNZQVwXLpZ9lQctjVGgrgfos6jP5kgo3deC2Sp
    WyLCKbhA4E2iuDXRrG6uPq4+vah116DryI7eCIY+8eVghK+hNlRqU8AC8szGD+nD
    mwoqVUUHpdO6+15qV2wZEugpFL9qDr+LZPXcrZ5CePX6oQKBwFEcwNu8jdPSkZUR
    S4nq32BlyLzgjOD6g1KqEfRx3tvtTNJmh/ssoo7mFkd2NHzI9ek1GRB8YyK0Ul3U
    SibajcQCtBMv+DTbx0vHoiMcaweRPSVsky8SikyzlG9AgwYE983uNjA7TI3ITTjL
    XbcDsZ/3gxW9gognD8NjvY7KEe/xFb23cTQeZ+fJ29yMgc6V+PqI7DZo6T0dCNv2
    l/UpZvhYzfOQUglA6zq+PQjheddxY3artrh41h9qh9URujKbGQKBwQDdf/zBrw6/
    vxSiGJUwRjiZMQJJi9lJBOXInNQLmJAS545AgZL+txrjm3I/wnxUgZThEHRn55/X
    IEV4cayisJPesEL8g9lQzvLlhpo76OEaLDry07R4bhTEo70zaZ2zeqwiOdlt6CF4
    SdDF6gx9jj/JhH/PK+JgTJbwl9SnFcu461Q6bdv3BwefWK1KFAEZIoCBvHqaLKUh
    lkUfbDy+EWBE6VsU/oJ4PM+1AXcpFt/eXBXC5fwGt/yV5zyiTz5UujY=
    -----END RSA PRIVATE KEY-----
  rsa_public: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQBILkZ5XEHdqdVYaqlz0arFwwOWOU5X/o1cetqnHj6w3e790PlDPouyxFvl8mhHX3ddEUUkq4WksAjd59giS4Tr3EKgXT0kLILtppCkJfDhHpDLIYb7yHzrEAH8HL87jlAhCwtXIb2/9T/QDqumUTEh1wV0iGMA238caIenbWNjHTDuwVUPv7tUNcdTFwseXu0pblU9GNwb2QO3zyLB6oMiXHjvvZ0ErtHzb9VkjEnI6QRoEuDuCJJIGrPLqGQDuW2RHIHFnlccL0X3OQY/Ud/Pyy/wt2KX+dcQxKI63S4n9CXJL214mrlyUTz+aYJf1V7bjLt9MeDwDaMlfKPvjlSi7S/ICc4KvgbGz8rtE5GrmMAQkcQEiAzPG76Mhj21R/EfHbISNG+amJYkq1LWaLlclbo+zpwSNUKRE/WEZcwiCP2dgm9tn/tdKwD4TG29O0VQTE74Syu4gu3lSDTRJ6jlg8/eDkW0/AcYYn1Oe5GLJbVlPz+oIigrN7XWjRy+8= main@JG-ARCH
    
runcmd:
    # Setting up Node
  - curl -sL "https://deb.nodesource.com/setup_14.x" | sudo -E bash -
  - apt-get install -y nodejs
    #Setting up mongodb
  - curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc -o /home/azureuser/key.txt
  - apt-key add /home/azureuser/key.txt
  - rm /home/azureuser/key.txt
  - add-apt-repository "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse"
  - apt-get update -y
  - apt-get install -y mongodb-org
  - systemctl start mongod
  - systemctl enable mongod
    #Adding ssh key to host keys
  - eval "$(ssh-agent -s)"
  - ssh-add /etc/ssh/ssh_host_rsa_key
    #Pulling repo
  - git clone git@github.com:JoaquimXG/podcolours.co.uk.git app
  - cd app
    #Pulling secrets file (Stored in Azure)
  - curl "https://xjgpersonalstorage.blob.core.windows.net/envvars/.env?sp=r&st=2021-09-23T10:55:10Z&se=2021-09-23T18:55:10Z&spr=https&sv=2020-08-04&sr=b&sig=SH4N%2BWzhQ633ev4mhLNpj1AvqgT6LghiE2VbgsUZ9aw%3D" -o .env
    # Creating Mongo Admin User
  - chmod +x ./createMongoUsers.sh
  - bash createMongoUsers.sh
    # Enabling Mongo Access Controls
  - >-
    echo "security:" >> /etc/mongod.conf
  - >-
    echo "  authorization: enabled" >> /etc/mongod.conf
  - systemctl restart mongod
    # Install app dependancies
  - npm ci --production
    # Setup Datbase from template
  - npm run setupDb
  - npm start

final_message: "The system is finally up, after $UPTIME seconds"
